---
kind: pipeline
name: build

clone:
  depth: 50

steps:
  - name: hadolint
    image: hadolint/hadolint:latest-debian
    commands:
      - hadolint --version
      - hadolint  Dockerfile

  - name: publish
    image: plugins/docker
    environment:
      APPVERSION: ${DRONE_TAG}
    settings:
      repo: lukasbahr/prometheus-raspberrypi-temp-exporter
      tags: 
        - ${DRONE_TAG}
      dockerfile: Dockerfile
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASSWORD
      build_args:
        - DRONE_TAG=${DRONE_TAG}
    when:
      event:
        - push
        - tag