---
kind: pipeline
name: build

clone:
  depth: 50

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: publish
    image: plugins/docker
    settings:
      repo: lukasbahr/raspbi-vcgencmd-exporter
      tags: arm32v6
      #tags: $DRONE_TAG
      dockerfile: Dockerfile
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASSWORD
    when:
      event:
        - push
        - tag