version: "3.3"
services:

  exporter:
    restart: always
    container_name: exporter
    image: docker.io/lukasbahr/prometheus-raspberrypi-temp-exporter:v0.0.1
    environment:
      - APPVERSION=v0.0.3
    expose: 
      - 9234
    networks:
      - pi


networks: 
  pi: 
    external: true
